sequenceDiagram
    title Handläggare väljer ett ärende
    participant RTF_regel_manuell
    participant folkbokford
    participant arbetsgivare
    participant OUL
    participant portal

    note over portal: Handläggare listar sina uppgifter
    portal ->> OUL: API: GET /uppgifter/handlaggare/{handlaggare_id}
    OUL -->> portal: (lista av uppgift_id, regeltyp, kundbehovsflode_id)
    note over portal: Handläggare väljer en av sina uppgifter


    portal ->> RTF_regel_manuell: API: GET /regel/VAH_RTF_manual/{kundbehovsflode_id}
    note over RTF_regel_manuell, portal: uppgiftens url renderas

    RTF_regel_manuell -->> portal: (all info som frontend_url behöver)

    note over portal: uppgiftens url renderas