sequenceDiagram
    title Handläggare väljer ett ärende
    participant RTF_rule_manual
    participant folkbokford
    participant arbetsgivare
    participant OUL
    participant uppgiftsregister
    participant portal
    participant frontend

    frontend ->> portal: API: GET /uppgifter/handlaggare/{handlaggare_id}
    portal ->> OUL: API: GET /uppgifter/handlaggare/{handlaggare_id}
    OUL -->> portal: (lista av uppgift_id, uppgiftsregister_id, frontend_url, beskrivning, personnummer, datum)
    portal -->> frontend: (lista av uppgift_id, uppgiftsregister_id, frontend_url, beskrivning, personnummer, datum)
    note over frontend: Handläggare väljer en av sina uppgifter


    frontend ->> RTF_rule_manual: API: GET /regel/VAH_RTF_manual/{uppgift_id}
    RTF_rule_manual ->> folkbokford: API: GET /folkbokford/info/{personnummer}
    folkbokford -->> RTF_rule_manual: person (namn, kön, adress ...)

    RTF_rule_manual ->> arbetsgivare: API: GET /arbetsgivare/info/{personnummer}
    arbetsgivare -->> RTF_rule_manual: anställningsinfo (period, orgnummer, orgnamn)

    RTF_rule_manual -->> frontend: (all info som frontend_url behöver)

    note over frontend: uppgiftens url renderas