sequenceDiagram
    title Maskinell regel svarar med fel - handläggning initierar ny begäran till VAH
    participant Kund
    participant VAH
    participant RTF_regel_maskinell
    participant handlaggning

    Kund ->> handlaggning: POST /yrkande (erbjudandeId, yrkandeFrom/To, individYrkandeRoller, produceradeResultat)
    note over handlaggning: Skapa nytt flöde med nytt yrkandeId
    handlaggning -->> Kund: (handlaggning inkl. yrkande)
    note over handlaggning: Skapar ny handläggning

    note over handlaggning: Initiera nytt handläggningsärende för erbjudandet
    handlaggning ->> VAH: Kafka: HandlaggningRequestMessage(handlaggningId) (till erbjudandets topic)

    note over VAH: Initiera maskinell regel

    VAH ->> RTF_regel_maskinell: Kafka: RegelRequestMessage (handlaggningId, AktivitetsId)

    note over RTF_regel_maskinell: Se exempel ratt_till_forsakring_maskinell.mmd

    RTF_regel_maskinell ->> VAH: Kafka: RegelResponseMessage (handlaggningId, status=ERROR)
    note over VAH: Fel från maskinell regel. Ingen manuell utredning initieras.

    VAH ->> handlaggning: Kafka: HandlaggningResponseMessage (handlaggningId, resultat=FEL)
