sequenceDiagram
    title Kunden har rätt till försäkringen efter manuell utredning
    participant Kund
    participant VAH_flode
    participant RTF_rule_automatic
    participant RTF_rule_manual
    participant status_subscribers
    participant folkbokford
    participant arbetsgivare
    participant OUL
    participant uppgiftsregister
    participant portal
    participant frontend

    Kund ->> VAH_flode: Swagger: VAH ansökan (personnummer)
    note over VAH_flode: new processId
    VAH_flode ->> RTF_rule_automatic: Kafka: VahRtfRequestMessage (processId, personnummer)
    RTF_rule_automatic ->> folkbokford: API: GET /folkbokford/{personnummer}
    folkbokford -->> RTF_rule_automatic: False
    RTF_rule_automatic ->> arbetsgivare: API:  GET /arbetsgivare/{personnummer}
    arbetsgivare -->> RTF_rule_automatic: True
    note over RTF_rule_automatic: kolla om regel uppfylld
    RTF_rule_automatic ->> VAH_flode: Kafka: VahRtfResponseMessage (processId, personnummer, UTREDNING)
    note over VAH_flode: Ej godkänt. Starta manuell utredning

    VAH_flode ->> RTF_rule_manual: Kafka: VahRtfRequestMessage (processId, personnummer)
    RTF_rule_manual ->> OUL: Kafka: UppgiftRequest (uppgiftsregister_id: "VAH_RTF", frontend_url, personnummer, datum)
    note over OUL: Skapa ny operativ uppgift
    OUL ->> status_subscribers: Kafka: UppgiftStatus (uppgifts_id, status=Ny)
    frontend ->> portal: API: POST /uppgifter/handlaggare/{handlaggare_id}
    portal ->> OUL: API: POST /uppgifter/handlaggare/{handlaggare_id}
    note over OUL: tilldela uppgift till handläggare
    OUL ->> status_subscribers: Kafka: UppgiftStatus (Tilldelad)
    OUL -->> portal: (uppgiftsregister_id, uppgift_id, frontend_url, personnummer, datum)
    portal -->> frontend: (uppgiftsregister_id, uppgift_id, frontend_url, personnummer, datum)
    note over frontend: Tilldelad uppgift visas för handläggare
    note over frontend: frontend_url renderar tilldelad uppgift
    frontend ->> RTF_rule_manual: Get all data for uppgift
    RTF_rule_manual ->> folkbokford: API: GET /folkbokford/info/{personnummer}
    folkbokford -->> RTF_rule_manual: person (namn, kön, adress ...)

    RTF_rule_manual ->> arbetsgivare: API: GET /arbetsgivare/info/{personnummer}
    arbetsgivare -->> RTF_rule_manual: anställningsinfo (period, orgnummer, orgnamn)

    RTF_rule_manual -->> frontend: (all info...)
    note over frontend: Handläggare utför manuell uppgift
    frontend ->> portal: API: PATCH /uppgifter/{uppgift_id} (update state)
    portal ->> OUL: API: PATCH /uppgifter/{uppgift_id} (update state)
    OUL -->> portal: OK
    portal -->> frontend: OK
    frontend ->>  RTF_rule_manual:POST DONE...








    OUL ->> status_subscribers: Kafka: UppgiftStatus (Avslutad)

    note over RTF_rule_manual: kolla om regel uppfylld
    RTF_rule_manual ->> VAH_flode: Kafka: VahRtfResponseMessage (processId, personnummer, JA)

    VAH_flode ->> Kund: Kafka: VAH ansökan resultat (processId, personnummer, Godkänd)
