sequenceDiagram
    title Kunden har rätt till försäkringen efter manuell utredning
    participant Kund
    participant VAH
    participant RTF_regel_maskinell
    participant RTF_regel_manuell
    participant handlaggning

    note over RTF_regel_manuell: Subscribe på oul-status uppdateringar

    Kund ->> handlaggning: POST /yrkande (erbjudandeId, yrkandeFrom/To, individYrkandeRoller, produceradeResultat)
    handlaggning -->> Kund: (yrkande)
    note over Kund: Hämta yrkandeId från yrkande

    Kund ->> handlaggning: POST /handlaggning (yrkandeId)
    note over handlaggning: Skapa nytt flöde med nytt yrkandeId
    handlaggning -->> Kund: (handlaggning inkl. yrkande))

    note over handlaggning: Initiera nytt handläggningsärende för erbjudandet
    handlaggning ->> VAH: Kafka: HandlaggningRequestMessage(handlaggningId) (till erbjudandets topic)

    note over VAH: Initiera maskinell regel

    VAH ->> RTF_regel_maskinell: Kafka: RegelRequestMessage (handlaggningId, AktivitetsId)

    note over RTF_regel_maskinell: Se exempel ratt_till_forsakring_maskinell.mmd

    RTF_regel_maskinell ->> VAH: Kafka: RegelResponseMessage (handlaggningId, Utfall=UTREDNING)
    note over VAH: Ej godkänt. Starta manuell utredning

    VAH ->> RTF_regel_manuell: Kafka: RegelRequestMessage (handlaggningId, AktivitetsId)

    note over RTF_regel_manuell: Se exempel ratt_till_forsakring_manuell.mmd

    RTF_regel_manuell ->> VAH: Kafka: RegelResponseMessage (handlaggningId, utfall)

    VAH ->> handlaggning: Kafka: HandlaggningResponseMessage (handlaggningId, resultat)

    handlaggning ->> Kund: Kafka: HandlaggningDoneMessage (handlaggningId)