sequenceDiagram
    title Restart av processinstans medan RTF manuell regel väntar på handläggare
    participant Administrator
    participant Workflow
    participant Handlaggning
    participant ErbjudandeTopic
    participant VAH
    participant RTF_regel_manuell
    participant OUL
    participant portal

    note over VAH,RTF_regel_manuell: VAH har skickat RegelRequestMessage till RTF_regel_manuell
    note over RTF_regel_manuell,portal: RTF_regel_manuell väntar på att handläggare ska slutföra manuell uppgift via portal

    Administrator ->> Workflow: POST /handlaggning/{handlaggningId}/process (med replyTo)
    Workflow ->> Handlaggning: HandlaggningAdapter: GET /handlaggning/{handlaggningId}
    Handlaggning -->> Workflow: (handläggning inkl. yrkande med erbjudandeId)
    Workflow ->> ErbjudandeTopic: GET /topic/{erbjudandeId}
    ErbjudandeTopic -->> Workflow: (Kafka topic associerat med erbjudande id)
    note over Workflow: Uppdatera replyTo i DB
    Workflow ->> VAH: Kafka: HandlaggningRequestMessage(handlaggningId) (till erbjudandets topic)
    note over VAH: Ny processinstans startas utan att avbryta pågående process
    Workflow -->> Administrator: (handlaggning inkl. yrkande)

    note over VAH: Ny processinstans exekveras (RegelRequestMessage skickas igen till RTF_regel_manuell m.m.)