sequenceDiagram
    title Initiering och avslut av process
    participant Kund
    participant Workflow
    participant ErbjudandeTopic
    participant Handlaggning
    participant VAH
    Kund ->> Workflow: POST /yrkande (erbjudandeId, yrkandeFrom/To, individYrkandeRoller, produceradeResultat, replyTo, ...)
    note over Workflow: Skapa nytt yrkande och handläggning
    Workflow ->> ErbjudandeTopic: GET /topic/{erbjudandeId}
    ErbjudandeTopic -->> Workflow: (Kafka topic associerat med erbjudande id)
    note over Workflow: Spara replyTo i DB
    Workflow ->> Handlaggning: HandlaggningAdapter: PUT /handlaggning (handläggning, yrkande)
    Handlaggning -->> Workflow: (Svar från Handlaggning...)
    Workflow ->> VAH: Kafka: HandlaggningRequestMessage(handlaggningId) (till erbjudandets topic)
    Workflow -->> Kund: (handlaggning inkl. yrkande)
    note over VAH: (Exekvering av process flöde, regler, etc)
    VAH ->> Workflow: Kafka: HandlaggningResponseMessage (handlaggningId, resultat)
    note over Workflow: Läs och ta bort replyTo topic från persistent lagring
    Workflow ->> Kund: Kafka: HandlaggningDoneMessage(handlaggningId) (till replyTo topic)
