#
# Det här är bara ett tillfälligt workflow! Bör slå isär det här repot och sedan följa template-projekt.
#
name: Maven CI

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    strategy:
      #max-parallel: 3
      fail-fast: false
      matrix:
        java: ["25"]
        os: ["ubuntu-latest"]
        project: ["regler", "folkbokford"]
    name: Java ${{ matrix.Java }} (${{ matrix.os }}) - ${{ matrix.project }}
    env:
      skip-automatic-fk-code-standard-apply: true
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: "0"
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Create Maven settings.xml
        run: |
          mkdir -p "$RUNNER_TEMP/maven"
          cat <<'EOF' > "$RUNNER_TEMP/maven/settings.xml"
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github--Forsakringskassan--repository</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: "Maven build"
        shell: bash
        run: |
          java -version
          javac -version
          cd ${{ matrix.project }}
          ./mvnw -T 1C -s $RUNNER_TEMP/maven/settings.xml verify
          cd ..

      - name: Publish Build
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-${{ github.run_number }}-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.project }}
          path: ${{ github.workspace }}
